server:
  port: 8084

spring:
  application:
    name: pay-service
  cloud:
    config:
      name: gameinfo, kakao-service
    openfeign:
      circuitbreaker:
        enabled: true
  config:
    import:
      - "optional:configserver:http://config-service:9088"
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console